/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card/Card.vue')['default']
    CarouselList: typeof import('./src/components/CarouselList/CarouselList.vue')['default']
    CreateWorkCardBox: typeof import('./src/components/Work/CreateWorkCardBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./src/components/CarouselList/Carousel/HelloWorld.vue')['default']
    MaskCard: typeof import('./src/components/MaskCard.vue')['default']
    MessageBox: typeof import('./src/components/Card/MessageBox.vue')['default']
    ScrollingCard: typeof import('./src/components/CarouselList/Carousel/ScrollingCard.vue')['default']
    ScrollingCardList: typeof import('./src/components/CarouselList/Carousel/ScrollingCardList.vue')['default']
    Skills: typeof import('./src/components/Skills/Skills.vue')['default']
    TopBar: typeof import('./src/components/topBar.vue')['default']
    Work: typeof import('./src/components/Work/Work.vue')['default']
    WorkCard: typeof import('./src/components/Work/WorkCard.vue')['default']
    WorkCardBox: typeof import('./src/components/Work/WorkCardBox.vue')['default']
  }
}
